apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: startpage
  name: startpage-pvc
  namespace: startpage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi