apiVersion: v1
kind: Service
metadata:
  name: startpage
  namespace: startpage
spec:
  ports:
  - name: startpage
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    pod-label: startpage